version: "3.9"

services:
  server:
    build:
      context: ./server
    container_name: infobuddy-server
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  client:
    build:
      context: ./client
      args:
        # Exposed to browser bundle; for local compose use localhost
        NEXT_PUBLIC_SERVER_URL: "http://localhost:8000"
    container_name: infobuddy-client
    ports:
      - "3000:3000"
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped
